name: Deploy Flutter Web su GitHub Pages

on:
  push:
    branches: [ Develop ]   # cambia se il tuo branch principale ha un altro nome
  workflow_dispatch:     # permette di avviarlo anche a mano

permissions:
  contents: write        # serve per scrivere sul branch gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Installa Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Dipendenze
        run: flutter pub get

      - name: Build web
        run: flutter build web --release --base-href "/${{ github.event.repository.name }}/"

      - name: Pubblica su gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages
